### ISSUE TITLE
Chapter 2: Use an ASP.NET Core web application and call a protected web API on Azure AD for Customers

### ISSUE THREAD

**Issue by bappadityams** [Azure-Samples/ms-identity-ciam-dotnet-tutorial#41]
Trying to execute 2-Authorization - 1-call-own-api-aspnet-core-mvc in External ID tenant.

My service api, client  app registration and appsettings are correct. But getting the below error - 

Response content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
fail: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
fail: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Message: IDX20803: Unable to obtain configuration from: 'https://trialexternalidfordemobban.ciamlogin.com/10e93a61-a289-4484-9a82-799587f1f2a9/.well-known/openid-configuration'. Will retry at '10/2/2023 7:35:20 PM +00:00'. Exception: 'System.IO.IOException: IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel) 
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'., InnerException: System.IO.IOException.
fail: Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter[0]
      Message: IDX40001: Issuer: 'https://sts.windows.net/10e93a61-a289-4484-9a82-799587f1f2a9/', does not match any of the valid issuers provided for this application. , InnerException: System.InvalidOperationException.

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
>Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bgavrilMS** [comment]
Does this still repro @bappadityams ? I can see that I get a response from https://trialexternalidfordemobban.ciamlogin.com/10e93a61-a289-4484-9a82-799587f1f2a9/.well-known/openid-configuration'

**Comment by AlbertoPa** [comment]
@bgavrilMS yes, I think it still reproduces. I have the same issue with an asp.net core web api with Entra ID for customers preview.

The problem is not the URL in the error message, which is what Entra responds to the web API, but the configuration of the web API. Specifically, if I follow the sample or the documentation and set:

``
Instance: "https://{{tenant subdomain}}.ciamlogin.com/"
``

I receive the same error.

**Comment by AlbertoPa** [comment]
The solution for me was to set accessTokenAcceptedVersion to 2.

**Comment by bgavrilMS** [comment]
Yes, we are discussing to make this the default. Thank you for the feedback.

**Comment by AlbertoPa** [comment]
You are welcome. I found the answer in the known issues a few minutes after posting: sorry for the inconvenience :-)
