### ISSUE TITLE
DeviceCode sample does not work using Entra External ID tenant

### ISSUE THREAD

**Issue by Johno-ACSLive** [Azure-Samples/ms-identity-ciam-dotnet-tutorial#53]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create a Entra External ID tenant and follow the remaining instructions. The arcticle [here](https://medium.com/the-new-control-plane/authenticating-with-entra-external-id-for-customers-ciam-with-the-device-code-flow-f006d0ac87ef) provides details on the steps and issues.

### Any log messages given by the failure
> The URL provided in devicecode.VerificationUrl is "https://microsoft.com/devicelogin" but when logging in with a local account the follow error is displayed "AADSTS500208: The domain is not a valid login domain for the account type". The article [here](https://medium.com/the-new-control-plane/authenticating-with-entra-external-id-for-customers-ciam-with-the-device-code-flow-f006d0ac87ef) documents the issue.

### Expected/desired behavior
> The correct URL for the domain should be provided e.g. "https://tenant_sub_domain.ciamlogin.com/common/oauth2/deviceauth". I'm not sure if this is a documentation issue or Microsoft.Identity.Client / MSAL issue.

### OS and Version?
> Windows 11

### Versions
> .NET 8 console app using Microsoft.Identity.Client version 4.59.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Johno-ACSLive** [comment]
Seems to be a CIAM issue, being tracked here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4666

**Comment by bgavrilMS** [comment]
Closing for tracking in MSAL
