### ISSUE TITLE
Getting the following error after I login to my Azure B2C account in IOS

### ISSUE THREAD

**Issue by billyjacobs2014** [Azure-Samples/ms-identity-ciam-dotnet-tutorial#69]
### This issue is for:
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I used the sample provided from git clone https://github.com/Azure-Samples/ms-identity-ciam-dotnet-tutorial.git
I followed the instructions and setup everything as requested. 
I am able to login successfully but the SignInUserAndAcquireAccessToken method throws an exception on the last line:
`return this.AuthResult.AccessToken;` because AuthResult is null. See log message below for issue with Entitlements.plist

I am using automatic provisioning to may apple developer account. I have KeyChain checked in the Entitlements.plist file. The contents of my Entitlements.plist file is what came with the sample which has:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>keychain-access-groups</key>
        <array>
            <string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
        </array>
    </dict>
</plist>`

I added the override of the OpenUrl method in my AppDelegate.cs file, which does not get called. Not sure if that matters? I also don't understand why the instructions say to ensure this is used but yet it is not in the sample code. 

Give the error below I have done extensive research and I don't see what I have done wrong. 

I have also looked at this url given in the error message which appears to be an older version of what you have in the sample above:
https://aka.ms/msal-net-enable-keychain-groups

Any assistance would be greatly appreciated. 

### Any log messages given by the failure 
>
NOTE: I replaced my actual APP ID Prefix with MYAPPREFIX below. The actual error has the correct APP ID Prefix
ErrorCode: missing_entitlements
Microsoft.Identity.Client.MsalClientException: The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group 'MYAPPREFIX.com.microsoft.msalcache' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements.
### Expected/desired behavior
> To get a valid AuthToken and have the info displayed on the page as specified in the tutorial.

### OS and Version?
> Windows 11, Visual Studio 17.10.0, .net 7.0, mac OS Ventura13.6.3

**Comment by billyjacobs2014** [comment]
I figured it out. Your sample has an issue. In your entitlements.plist you have **_com.microsoft.adalcache_** but it should be **_com.microsoft.msalcache_**. 

The code that configures it is

```
private void InitializePublicClientApplicationBuilder()
{
    this.PublicClientApplicationBuilder = PublicClientApplicationBuilder.Create(AzureAdConfig.ClientId)
        .WithExperimentalFeatures() // this is for upcoming logger
        .WithAuthority(string.Format(AzureAdConfig.Authority, AzureAdConfig.TenantId))
        .WithLogging(new IdentityLogger(EventLogLevel.Warning), enablePiiLogging: false)    // This is the currently recommended way to log MSAL message. For more info refer to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging. Set Identity Logging level to Warning which is a middle ground
        .WithIosKeychainSecurityGroup("com.microsoft.msalcache");
}
```

**Comment by bgavrilMS** [comment]
This was fixed https://github.com/Azure-Samples/ms-identity-ciam-dotnet-tutorial/issues/66
